# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Setup

title: The path of Computer Science
tagline:          '计算机科学之路'
email: junzhou.ren.auditeur@lecnam.net
description: Tech. Blog of CS & Development
#baseurl: "./blog" # the subpath of your site, e.g. /blog
url: "https://renjunzhou.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DackRen
github_username:  DackRen

permalink: /blog/:year/:month/:day/:title/

paginate:         20

#permalink:        pretty
# Build settings
#markdown:         redcarpet
markdown: kramdown
theme: minima
highlighter:         true

gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

  # Custom vars
  # version:          2.0.0
  #
  # github:
  #   repo:           https://github.com/poole/lanyon
